project:
  type: website
  output-dir: docs

website:
  title: |
    <span style="display: flex;">Alif Dewantara</span>
    <span style="font-size: 12.5px; font-weight: normal; display: flex ;">Data · Tech · Historian</span>
  description: "Jejaring Pribadi"
  site-url : alifdwt.github.io
  search:
    location: navbar
    type: overlay
  favicon: img/favicon-32x32.png
#  sidebar:
#    style: docked
#    tools: 
#      - icon: github
#        href: https://github.com/alifdwt
  navbar:
    pinned: true
    logo: img/logo-circle.png
    left:
      - text: "About"
        file: about.qmd
      - text: "Proyek"
        file: proyek.qmd
      - text: "Blog"
        file: index.qmd
    right:
      - icon: twitter
        href: https://twitter.com/alifdwt
      - icon: linkedin
        href: https://www.linkedin.com/in/alifdwt/
      - icon: github
        href: https://github.com/alifdwt
      # Add RSS feed to navbar
      - icon: rss
        href: blog.xml
  page-footer:
    left: 
      - text: "© 2023 Musim Semi Peking"
    right:
      - href: https://www.quarto.org
        text: Dibuat oleh R dan Quarto
    
  page-navigation: true
format:
  html:
    theme:
      # - simplex
      - theme.scss
    toc: true
    toc-location: right
    code-link: true
    anchor-sections: true
    fig-cap-location: bottom
    fig-align: center
    fig-responsive: true
    reference-location: margin
    footnotes-hover: true
    highlight-style: dracula
    code-summary: Lihat Kode
    code-fold: true

editor: visual